export default [
  { name: 'Learn by doing', citation: 'Papert' },
  { name: 'Learn by teaching', citation: 'Schwartz' },
  { name: 'Failure is part of learning', citation: 'Jim Gee' },
  { name: 'We grow by persisting through challenges', citation: 'Duckworth' },
  { name: 'Everyone has the capacity to grow', citation: 'Dweck' },
  { name: 'Challenge is constant', citation: 'Vygotsky' },
  { name: 'Encourage choice' },
  { name: 'Immediate and continual feedback' },
  { name: 'Believe in students' },
  { name: 'Use student interests, interest-powered learning' },
  { name: 'Use rewards' },
  { name: 'Responsible for own learning, agency' },
  { name: 'Learning on their own, autonomy' },
  { name: 'Learning feels like play' },
  { name: 'Authentic audiences' },
  { name: 'Outcomes as the goal' },
  { name: 'Learning as the goal' },
  { name: 'Sense of belonging' },
  { name: 'Experience success' },
  { name: 'Develop competence and mastery' },
  { name: 'Applicability to real-world impact' },
  { name: 'Connecting to prior knowledge' }
];
